const HELP = {
  clientsCaseNeed: { title: 'Potřeba case managementu', text: 'Zvolte Ano, pokud klient potřebuje koordinovanou podporu více služeb nebo institucí. Poté doplňte datum zahájení a důvod.' },
  clientsCaseSince: { title: 'Začátek case managementu', text: 'Datum, od kterého je klient veden v režimu case managementu.' },
  clientsCaseReason: { title: 'Důvod case managementu', text: 'Stručně a věcně popište, proč klient potřebuje koordinaci podpory.' },
  clientsAiSummary: { title: 'AI souhrn zakázky', text: 'Vytvoří pracovní souhrn z klientské osy a evidovaných podpor. Výsledek vždy zkontrolujte.' },
  clientsDriveFolder: { title: 'Složka klienta', text: 'Založí klientskou složku v určené složce Google Drive a vytvoří nebo aktualizuje monitorovací list.' },
  clientsSupportHours: { title: 'Hodiny podpory', text: 'Součet vychází z uložených záznamů. U výkonů se používá interval OD–DO; individuální plán má započtenou jednu hodinu.' },
  iprSituation: { title: 'Popis situace', text: 'Popište výchozí situaci klienta, jeho zdroje, omezení, potřeby a podstatné bariéry stručně a věcně. Toto pole je povinné.' },
  iprGoals: { title: 'Cíle plánu', text: 'Každý cíl obsahuje popis, akční kroky a termín. Uložené cíle se nabízejí v zápisech jako vazba Cíl IP.' },
  iprGoalEvaluation: { title: 'Hodnocení cíle', text: 'Po označení cíle jako splněného doplňte slovní vyhodnocení. Používá se také při kontrole plnění cílů.' },
  iprFinalEvaluation: { title: 'Závěrečné vyhodnocení', text: 'Zobrazí se po splnění a vyhodnocení všech cílů. Shrňte výsledek celého plánu.' },
  aiGoalLink: { title: 'Cíl IP', text: 'Vyberte související cíl individuálního plánu. Pokud podpora na plán nenavazuje, použijte Jednorázovou zakázku.' },
  aiTime: { title: 'Čas podpory', text: 'Zadejte skutečný čas OD a DO. Trvání se vypočítá automaticky a započítává se do hodin podpory. Čas DO musí být pozdější.' },
  aiDelivery: { title: 'Forma poskytování', text: 'Vyberte ambulantní, terénní nebo telefonní formu. Pole je pro zápis individuální podpory povinné.' },
  aiSupportType: { title: 'Typ podpory', text: 'Vyberte skutečný druh poskytnuté podpory. Podle volby se mohou zobrazit další specifická pole.' },
  aiSupportArea: { title: 'Oblast podpory', text: 'Vyberte hlavní řešenou oblast. Údaj se používá při vyhodnocování projektových cílů a sociálního začlenění.' },
  aiSpecific: { title: 'Specifická pole', text: 'Pole odpovídají zvolenému typu podpory. Uvádějte pouze skutečně zjištěné nebo provedené činnosti.' },
  aiCasePartners: { title: 'Zapojení aktéři', text: 'Vyberte skutečně zapojené partnery z registru nebo doplňte další osobu ručně.' },
  aiGenerate: { title: 'AI návrh', text: 'Vytvoří pracovní návrh z vyplněných polí. Před uložením jej vždy věcně zkontrolujte a případně upravte.' },
  aiSave: { title: 'Uložení dokumentu', text: 'Uloží strukturovaný záznam i finální text do evidence, klientské osy a Google Sheetu. Chybějící povinná pole se zobrazí pod tlačítkem.' },
  aiOutput: { title: 'Výstup dokumentu', text: 'Toto je finální text ukládaný do evidence. Můžete jej vytvořit pomocí AI nebo napsat a upravit ručně.' },
  networkType: { title: 'Typ síťové aktivity', text: 'Vyberte skutečný typ aktivity. Údaj se ukládá do evidence a používá v přehledech a exportech.' },
  networkPlace: { title: 'Místo setkání', text: 'Vyberte přednastavené místo nebo doplňte jiné konkrétní místo jednání.' },
  networkAttendees: { title: 'Přítomné osoby', text: 'Vyberte pouze skutečně přítomné osoby. U porady jsou dostupné také role realizačního týmu.' },
  networkOutput: { title: 'Výstup zápisu', text: 'Finální text síťového zápisu. Používá se v uložené evidenci i v exportech.' },
  actorOrigin: { title: 'Zapojení aktéra', text: 'Rozlišuje stávajícího, nově zapojeného a potenciálního aktéra. Potenciální aktér bez doložené aktivity se do spolupracujících partnerů nepočítá.' },
  actorDate: { title: 'Datum zapojení', text: 'Vyplňuje se u nově zapojeného aktéra a pomáhá určit, zda byl partner zapojen v průběhu projektu.' },
  attendanceExport: { title: 'Prezenční listina', text: 'Vytvoří prezenční listinu pouze pro osoby zaškrtnuté v registru aktérů.' },
  dashboardPeriod: { title: 'Vykazované období', text: 'Omezuje záznamy používané pro výpočty hodin, indikátorů, cílů, rizik a partnerské sítě.' },
  dashboardExport: { title: 'Export klientů a podpory', text: 'Exportuje základní monitorovací údaje a souhrn podpory pro další zpracování. Nejde o úplnou klientskou dokumentaci.' },
  dashboardZor: { title: 'Texty pro ZOR', text: 'Připraví pracovní návrhy popisu pokroku za vybrané období. Nejprve vyberte konkrétní vykazované období.' },
  dashboard600: { title: 'Indikátor 600 000', text: 'Počítá klienty se 40 a více hodinami podpory, kteří mají kompletní monitorovací údaje.' },
  dashboard670: { title: 'Indikátor 670 102', text: 'Počítá klienty s podporou nad 0 a pod 40 hodin, kteří mají minimální registrační údaje.' },
  dashboardLongGoals: { title: 'Dlouhodobé cíle', text: 'U klientů se 40 a více hodinami vyžaduje započtení vazbu výkonu na konkrétní splněný a slovně vyhodnocený cíl IP.' },
  dashboardInclusion: { title: 'Sociální začlenění', text: 'Započítá krátkodobě podpořeného klienta s podporou nejméně ve čtyřech různých oblastech KA1 nebo KA2.' },
  dashboardPartners: { title: 'Partnerská síť', text: 'Počítají se jen partneři s doloženou aktivitou. Jednorázový partner má jednu aktivitu; aktivita za 90 dní vychází z posledního záznamu.' },
  dashboardRisks: { title: 'Kontrolní upozornění', text: 'Nejde o chyby aplikace, ale o údaje nebo situace, které mohou ohrozit správné vykazování projektu.' }
};

export { HELP };
